image: julia:1.6

before_script:
  - apt-get -qq update; apt-get -y install git
  - julia --project=@. -e "import Pkg; Pkg.build()"

unit_test:
  script:
    - julia --project=@. -e "import Pkg; Pkg.test()"
